In [29]:
import requests
import os
from pathlib import Path
import psycopg2
from skimpy import skim
import pandas as pd
from collections import defaultdict

In [30]:
conn=psycopg2.connect(user="postgres",host="localhost",port="5432",password="jaune2000",database="sandbox_db")
cur=conn.cursor()

In [31]:
def json_structure(obj, indent=0):
    
    prefix = "  " * indent
    if isinstance(obj, dict):
        for k, v in obj.items():
            print(f"{prefix}{k}: {type(v).__name__}")
            if isinstance(v, (dict, list)):
                json_structure(v, indent + 1)
    elif isinstance(obj, list) and obj:
        print(f"{prefix}[list of {len(obj)}]")
        json_structure(obj[0], indent + 1)  # inspect first item

In [32]:
def create_tables(cur):
    cur.execute("DROP TABLE IF EXISTS station_info")
    query="""CREATE TABLE station_info(
    station_id BIGINT  PRIMARY KEY,
    station_code VARCHAR(5) CHECK (length(station_code)=5),
    name VARCHAR(255),
    lat REAL,
    lon REAL,
    capacity INTEGER,
    rental_method VARCHAR(255)
    )"""
    cur.execute(query)

    cur.execute("DROP TABLE IF EXISTS station_status")
    query="""CREATE TABLE station_status(
    station_id BIGINT PRIMARY KEY,
    num_docks_available INTEGER,
    num_bikes_available INTEGER,
    is_installed BOOLEAN,
    is_returning BOOLEAN,
    is_renting BOOLEAN,
    last_reported BIGINT ,
    station_code VARCHAR CHECK(length(station_code)=5),
    num_bikes_mechanical INTEGER,
    num_bikes_ebike INTEGER
    )"""
    cur.execute(query)

In [ ]:
cur.execute("SELECT i.station_id,name,num_bikes_available FROM station_info i INNER JOIN station_status s ON i.station_id=s.station_id ORDER BY num_bikes_available")
print(cur.fetchall())

[(7304, 'Bassano -  Iéna', 0), (559980654, 'George V - Christophe Colomb', 0), (20689981670, 'Roossevelt - Impasse du Marché', 0), (478732841, 'Sebastopol - Rambuteau', 0), (10773448319, 'Clef des Champs - Albert Dhalenne', 0), (74805344, 'Pierre Charron - Champs-Elysées', 0), (76352106, 'Saint-Augustin', 0), (567884788, 'Vincent Auriol - Louise Weiss', 0), (210408693, 'Vaugirard - Monsieur le Prince', 0), (27363256, 'Thérèse - Opéra', 0), (266422568, 'Place Edmond Michelet', 0), (82584215, 'Place Lafayette', 0), (2705356759, 'Jean Jaurès - Paul Lafargue', 0), (17486828694, 'Charlot - Stade Gabriel Voisin', 0), (75345531, 'Turbigo - Française', 0), (128932790, 'Arsène Houssaye - Champs-Elysées', 0), (17174675707, 'Saint Pères - Saint Germain', 0), (1062807847, 'BNF - Bibliothèque Nationale de France', 0), (6245, 'Ventadour - Opéra', 0), (128843085, 'Place du Lieutenant Henri Karcher', 0), (128986726, 'Boétie - Ponthieu', 0), (276989966, 'Oratoire - Rivoli', 0), (37521, 'Petites Ecuries - Faubourg Poissonnière', 0), (569583918, 'Choiseul - Quatre Septembre', 0), (1062671597, 'Cossonnerie - Sébastopol', 0), (34742973, 'Place Balard', 0), (1057335613, 'Quai du Président Roosevelt - Pont Aval', 0), (1002738770, 'Lavandieres Sainte Opportune - Rivoli', 0), (210389577, 'Daunou - Louis le Grand', 0), (36391, 'Godot de Mauroy - Madeleine', 0), (1057091571, 'Esplanade du Foncet - Camille Desmoulins', 0), (36151, 'Favart - Italiens', 0), (66505511, 'François 1er - Montaigne', 0), (15383032, 'Place du Canada', 0), (55927887, 'Gabriel Lamé', 0), (210405211, 'Beaux-Arts - Bonaparte', 0), (54000465, 'Etienne Marcel - Montorgueil', 0), (128920403, 'Gare Saint-Lazare - Isly', 0), (259977414, 'Palais des Sports', 0), (66491368, 'Sorbonne - Ecoles', 0), (21372781592, 'Bateliers - Hippodrome', 0), (213957917, 'Wilson - Métallurgie', 0), (53999465, 'Place du Palais Royal', 0), (66505513, 'François 1er - Lincoln', 0), (16379269732, 'Président Roosevelt - Rouget de Lisle', 0), (213952930, 'Proudhon - Président Wilson', 0), (128882438, 'Institut du Monde Arabe - Saint-Germain', 0), (82337423, 'Varenne', 0), (125811629, 'Leredde - Tolbiac', 0), (82328045, 'Victoria - Place du Chatelet', 0), (20458224375, 'Vivienne - Petits Champs', 0), (6296, 'Institut de France', 0), (16043228469, 'Perrault - Place du Louvre', 0), (66491388, 'Alfred de Vigny - Place du Général Brocard', 0), (54000548, 'Quai Voltaire', 0), (287096529, 'Paul Klee - Place Augusta Holmes', 0), (1062797394, 'Place de la Madeleine - Royale', 0), (120827885, 'Messine - Place Du Pérou', 0), (1056979685, 'Bastille - Quai de la Rapée', 0), (99798962, 'Place Saint-André des Arts', 0), (653121023, 'Fief - République', 0), (21443204298, 'Coysevox - Lamarck', 0), (100902274, 'Roquépine - Malesherbes', 0), (54000549, 'Villersexel - Saint-Germain', 0), (221094844, 'Place Alphonse Deville', 0), (101753100, 'Henry Farman', 0), (42499285, 'Petit Palais', 0), (20636402451, 'Martignac - Grenelle', 0), (82335295, 'Saint-Séverin - Saint-Michel', 0), (535500589, 'Hôpital Européen Georges Pompidou', 1), (37420, 'Hauteville - Bonne Nouvelle', 1), (1057373549, 'Gare RER les Grésillons', 1), (653035822, 'Jeûneurs - Mulhouse', 1), (109609241, 'Colmar - Victor Hugo', 1), (417088374, 'Place Mongolfier', 1), (18099679477, 'Saint-Jacques - Soufflot', 1), (95073815, "Saint-Lazare - Place d'Estienne d'Orves", 1), (54000555, 'Jean Mermoz - Champs-Elysées', 1), (28233012, 'Marceau - Président Wilson', 1), (27415285, 'Place de Finlande', 1), (60667075, 'Georges V - François 1er', 1), (2002864789, 'Strasbourg - Saint-Denis', 1), (549480297, 'Halle Freyssinet - Parvis Alan Turing', 1), (27414527, 'Danielle Casanova - Opéra', 1), (66491386, 'Surcouf - Université', 1), (213676825, 'Pitié-Salpêtrière', 1), (208603342, 'Coquillière - Louvre', 1), (99886640, 'Place des Victoires', 1), (128940135, 'Marceau - Chaillot', 1), (311153993, 'Les Halles - Saint-Eustache', 1), (2514995690, 'Chabanais - Petits Champs', 1), (100770878, 'Poissy - Saint-Germain', 1), (101024234, 'Quai Panhard et Levassor', 1), (27415327, 'Courcelles - Pierre Demours', 1), (128890772, 'Bosquet - Saint-Dominique', 1), (205955605, 'Bienfaisance - Place de Narvik', 1), (66491389, 'Place de la Reine Astrid', 1), (66491390, 'Taitbout - Châteaudun', 1), (653085678, 'Berthier - Porte de Clichy', 1), (100759356, 'Montmartre - Etienne Marcel', 1), (486833337, 'Bachaumont - Montmartre', 1), (49474389, 'Artois - Berri', 1), (1805255023, 'Sèvres - Général Leclerc', 1), (323468705, 'Saint-Honoré - Musée du Louvre', 1), (21372647186, 'Versailles', 1), (82253759, 'Mairie du 7ème', 1), (213868408, 'Gare Routière de Saint Cloud', 1), (82590367, 'Place Marcel Sembat', 1), (210582921, 'Boudreau - Auber', 1), (216039437, 'Lamennais - Washington', 1), (210386007, 'Alger - Rivoli', 1), (42566291, 'Miromesnil - La Boétie', 1), (27414460, 'Danielle Casanova - Place Vendôme', 1), (54000553, 'Marignan - Champs-Elysées', 1), (647826568, 'Saint-Germain - Thenard', 1), (1057737444, 'Place Ginette Hamelin', 1), (653217067, 'Jules Guesde - Laennec', 1), (82336035, 'Saint-Germain - Ciseaux', 1), (54000552, 'Rome - Provence', 1), (1056986761, 'Terroirs de France - Lheureux', 1), (16659964929, 'Arsène Houssaye - Friedland', 1), (20703075041, 'Gare RER les Saules - Chandigarh', 1), (21372728303, 'Place Daydé - Ile Seguin', 1), (1002059045, 'Pont Neuf - Rivoli', 1), (210747224, 'Pirogues de Bercy - Libourne', 1), (128834707, 'Jean-Jacques Rousseau - Deux Ecus', 1), (653080383, "Bruneseau - Quai d'Ivry", 1), (1062742831, 'Place Joffre - Frédéric le Play', 1), (129061615, 'Primo Levi - Frigos', 1), (518825709, 'Jean Oestreicher - Porte de Champerret', 1), (1057405802, 'Place Nelson Mandela', 1), (19697809404, 'Matignon - Faubourg Saint-Honoré', 1), (478250062, 'Rivoli - Musée du Louvre', 1), (2515995748, 'Pesaro - Préfecture', 1), (1805401614, 'Sèvres-Gallieni', 1), (54000551, 'Galilée - Vernet', 1), (6293, 'Mairie du 2ème', 2), (462875227, 'Jules Guesde - Alsace', 2), (129029327, 'Victoire - Laffitte', 2), (13912564, 'Bruant - Vincent Auriol', 2), (237624030, 'Mathurins - Auber', 2), (220504949, 'Grande Truanderie - Saint-Denis', 2), (39626277, 'Lacuée - Lyon', 2), (49498164, 'Mairie du 8ème', 2), (100868590, 'Cité Vaneau', 2), (128889359, 'Champ de Mars - Cler', 2), (434419150, 'Bara - Henri Farman', 2), (117480156, 'Enfants du Paradis - Peupliers', 2), (102336814, 'Kléber - Gouverneur Général Eboué', 2), (49791363, 'Balzac - Champs Elysées', 2), (39799329, 'Faubourg Montmartre - La Fayette', 2), (36473, 'Cadet - La Fayette', 2), (210567545, 'Raspail - Varenne', 2), (1057296253, 'Regnault - Patay', 2), (121086415, 'Colisée - Champs-Elysées', 2), (476053320, 'Ecole Militaire - Place Joffre', 2), (128915891, 'Octave Gréard - Tour Eiffel', 2), (100893610, 'Bourdonnais - Tour Eiffel', 2), (128930462, 'Square Louis XVI', 2), (210573120, 'Hoche - Tilsitt', 2), (82577019, "Cité des Sciences et de l'Industrie", 2), (18023659071, 'Place Farhat Hached', 2), (18908512040, 'Place De Fontenoy - Saxe', 2), (76488849, 'Fernand Braudel - Vincent Auriol ', 2), (285001735, 'Vivienne - Montmartre', 2), (128989986, 'Place Georges Guillaumin', 2), (476155906, 'Saint-Antoine Sévigné', 2), (129014600, 'Rossini - Laffitte', 2), (82421994, 'Gare de Bercy', 2), (267976590, 'François Truffaut - Saint Emilion', 2), (100863462, "Musée d'Orsay", 2), (20033972555, 'ZAC des Louvresses', 2), (16965900639, 'Payenne - Square George Caïn', 2), (82448637, 'Suffren - Pérignon', 2), (30550, 'Mairie du 9ème', 2), (653048150, 'Jussieu - Guy de la Brosse', 2), (39296638, 'Berri - Haussmann', 2), (49403716, 'Commandant Rivière', 2), (11063317380, 'Sèvres - Maréchal Juin', 2), (63297, "Eglise d'Auteuil", 2), (16210188070, 'Convention - Campus de Bobigny', 2), (128884445, 'Constantine - Université', 2), (66491372, 'M.- A. Lagroua Weill-Hallé -  F. Dolto', 2), (1057045129, 'Cimetière de Boulogne-Billancourt', 2), (653114003, 'Dôme - République', 2), (213677219, 'Brillat-Savarin - Küss', 2), (101015227, 'Chevaleret - Louise Weiss', 2), (1057203651, 'Stade de France - Francis de Pressensé', 2), (2515049357, 'Erasme - Ulm', 2), (128841079, 'Cambon - Rivoli', 2), (210328645, 'Place André Malraux', 2), (101761298, 'Place du Moulin de Javel', 2), (210396518, 'Estrapade - Ulm', 2), (129038848, 'Enghien - Faubourg Poissonnière', 2), (85147829, 'Hôtel de Ville de Boulogne Billancourt', 2), (27414358, 'Saint-Honoré - 29 juillet', 2), (82379648, 'Lisbonne - Monceau', 2), (494183852, 'La Motte-Picquet - La Tour Maubourg', 2), (54001189, "Chaussée d'Antin - Haussmann", 2), (6352, 'Saint-Bon - Rivoli', 2), (593238093, "Victoire - Chaussée d'Antin", 2), (210582231, "Londres - Place d'Estienne d'Orves", 2), (55664548, 'Charonne - Faubourg Saint-Antoine', 2), (1057354004, 'Chemin de Bretagne', 2), (100769544, 'Harpe - Saint-Germain', 3), (84979504, "Provence - Chaussée d'Antin", 3), (20235746379, 'Square Bela Bartok', 3), (437741660, 'Saint-Denis - Rivoli', 3), (315022587, 'Malesherbes - Place de la Madeleine', 3), (2515855808, 'Madeleine Vionnet', 3), (20706822746, 'Chemin Des Mèches - Marc Seguin', 3), (20699589412, 'Suisses - Colonel de Rochebrune', 3), (100798076, 'Danton - Serpente', 3), (20702936749, 'Adrien Raynal - Verger', 3), (54000536, 'Saint-Fiacre - Poissonière', 3), (20703011127, 'Dr Calmette', 3), (19179850066, 'Centre Hospitalier Intercommunal de Créteil', 3), (323616530, "Quai de l'Horloge - Pont Neuf", 3), (19697937136, 'Charles de Gaulle', 3), (10647608657, 'Dora Maar - Nadia Guendouz', 3), (213676294, 'Chevaleret - Tolbiac', 3), (101763163, 'Desaix - Edgar Faure', 3), (7234, 'Colonel Pierre Avia', 3), (66491366, 'Saint-Marc - Feydeau', 3), (82387816, 'Bertie Albrecht - Hoche', 3), (213685514, 'Place Robert Guillemard', 3), (78374110, 'Square Pierre Lazareff', 3), (49423507, 'Pau Casals - Neuve Tolbiac', 3), (129143598, 'Pierret - Madrid', 3), (20497547989, 'Place du Général Leclerc', 3), (41219552, 'Saint-Benoît - Jacob', 3), (54000592, 'Balard - Montagne de la Fage', 3), (129026597, 'Caumartin - Provence', 3), (362869414, 'Hôpital Bégin', 3), (559595472, 'Suffren - Champ de Mars', 3), (491687415, 'Delizy - Louis Nadot', 3), (1057730786, 'Halles - Bourdonnais', 3), (19331917084, 'Lycée Saint Exupéry - Juliette Savar', 3), (54000544, 'Jussieu - Fossés Saint-Bernard', 3), (84958519, 'Arcole - Notre-Dame', 3), (54000593, "Longchamp - Place d'Iéna", 3), (210568512, 'Assemblée Nationale', 3), (85152599, 'Le Corbusier - Jean Jaurès', 3), (82571110, 'Verdun - Place Henri IV', 3), (34300292, 'Argenson - Château', 3), (15412563, 'Square Desnouettes', 3), (6515, 'Rougemont - Poissonnière', 3), (27415012, 'Bercy.', 3), (335780498, 'Greneta - Sebastopol', 3), (15308782, 'Sommerard - Saint-Jacques', 3), (419991048, 'Pont de Levallois-bécon ', 3), (252339799, 'Edouard Vaillant - Paul-Adolphe Souriau', 3), (37874517, 'Saint-Sulpice', 4), (27269170, 'Quai aux Fleurs - Pont Saint-Louis', 4), (129016495, 'Taitbout - La Fayette', 4), (214097180, 'Paul Doumer - Stalingrad', 4), (16043242148, "Charles de Gaulle - Rue de l'Alma", 4), (66491367, 'Beaubourg - Michel-le-Comte', 4), (42603855, 'Liège - Moscou', 4), (210395439, 'Centre Georges Pompidou', 4), (15377776, 'Paul Valery - Victor Hugo', 4), (210397939, 'Thouin - Cardinal Lemoine', 4), (1021176825, 'Billancourt - Général Leclerc ', 4), (468843711, "Saint Georges - d'Aumale", 4), (506455295, 'Général Martial Valin - Pont du Garigliano', 4), (66499894, 'Sainte-Elisabeth - Turbigo', 4), (653102462, 'Lampes', 4), (213848056, 'Parvis Corentin Celton', 4), (66491371, 'Pierre Sarrazin - Saint-Michel', 4), (27363323, 'Laffitte - Italiens', 4), (42341698, 'Cléry - Montmartre', 4), (653083263, 'Lucien Bossoutrot - Général Martial Vallin', 4), (1057319366, 'Quai de la Gare - Pont de Bercy', 4), (19495480499, 'Prague - Théophile Roussel', 4), (38263504, 'Place Jacques Madaule', 4), (213684314, 'Fédération - Suffren', 4), (101013666, 'Bercy - Villot', 4), (15397468, 'Maison de Radio - France', 4), (443654970, 'Française - Etienne Marcel', 4), (15409531, 'Méchain - Faubourg Saint-Jacques', 4), (54000466, 'Uzès - Montmartre', 4), (128874528, 'Temple - Haudriettes', 4), (269953055, 'Quai Marcel Boyer - Victor Hugo', 4), (54000561, 'Lamartine - Faubourg Montmartre', 5), (54000546, 'Sénat - Condé', 5), (129132870, 'Nationale - Place Jules Guesde', 5), (1074347188, 'Champs de Manoeuvre - Cartoucherie', 5), (29327, 'Stade Auguste Delaune', 5), (54000626, 'Madame de Sanzillon - Mozart', 5), (380891087, 'Place de la Bastille - Bourdon', 5), (653050378, 'Square René Viviani - Montebello', 5), (1055553396, 'Mornay - Sully', 5), (17225742003, 'Louis Armand - Bernard Palissy', 5), (66489651, 'Louis le Grand - Italiens', 5), (2515885093, 'Waldeck Rochet - Germaine Tillon', 5), (933214552, 'Guynemer - Séverine', 5), (72765603, 'Boulangers - Cardinal Lemoine', 5), (1765749389, 'Karl Marx', 5), (458086607, 'Président Wilson - Baudin', 5), (54000560, 'Geoffroy - Marie', 5), (96512532, 'Joseph Sansboeuf - Saint Lazare', 5), (54000550, 'Rapp - Place du Général Gouraud', 5), (1020700136, 'Neuve Saint-Pierre - Beautreillis', 5), (37903195, 'Transvaal - Charles de Gaulle ', 5), (653091677, "Place de l'Europe - Alfortville", 5), (210751059, 'Hôpital - Campo-Formio', 5), (368766689, 'Westermeyer - Paul Vaillant-Couturier', 5), (27363362, 'Seine - Flandre', 5), (442739463, 'Place de la République - Temple', 5), (331153695, 'Square Emile - Chautemps', 6), (101011685, 'Charenton - Prague', 6), (1063410400, 'Alouettes - Maréchal de Lattre de Tassigny', 6), (312870435, 'Dunkerque - Trudaine', 6), (213875650, 'Henri Ste-Claire Déville - Paul Héroult', 6), (54000573, 'Cardinal Lavigerie', 6), (54000632, 'Paul Vaillant-Couturier - Victor Hugo', 6), (653222953, 'Mairie de Rosny-sous-Bois', 6), (16529911795, 'Porte de Versailles', 6), (404947652, 'Place Fernand Forest', 6), (27363389, 'Bercy - Traversiére', 6), (15163771, 'George Sand - Jean de La Fontaine', 6), (568135465, 'Paul Vaillant Couturier - Chaptal', 6), (653073004, 'Tremblay - Lac des Minimes', 6), (586539770, 'Marne - Germain Dardan', 6), (1190800638, 'Ranelagh - Maison de la Radio', 6), (16930981813, 'Gabriel Péri - Place de la Libération', 6), (653122771, 'Marc Sangnier - Division Leclerc', 6), (653125838, "Cours de l'Ile Seguin - Parc Billancourt", 6), (653042442, 'Place aux Étoiles', 6), (213685863, 'Parc Suzanne Lenglen', 6), (7261, 'Athènes - Clichy', 6), (11580442, 'Geoffroy-Saint-Hilaire - Saint-Marcel', 6), (210399835, 'Panthéon - Valette', 6), (653203262, 'Parc Pierre Lagravère', 6), (213690256, 'Place du Maréchal Juin - Péreire', 6), (271540743, 'Gare de Clichy-Levallois ', 6), (17451195211, 'Jean Bouin - Gouverneur Général Eboué', 6), (128887067, "Ségur - d'Estrées", 6), (17638171254, 'Charles de Gaulle - Louis Philippe', 6), (15461933, 'Parc Monceau', 6), (19186208004, 'Stade de la Habette', 6), (27414512, 'Caire - Dussoubs', 6), (54000634, 'Bineau - Louise Michel', 6), (224598098, 'Dunois - Clisson', 6), (653205656, 'Gare de la Garenne-Colombes', 6), (2515636592, 'Mstislav Rostropovitch - Berthier', 6), (338824395, 'Bourse du Travail', 6), (128880156, 'Archives - Rivoli', 6), (27296946, 'Square Claude Bernard', 6), (100855693, 'Sabot - Rennes', 6), (256561528, 'Eugène Oudiné - Dessous Des Berges', 7), (653123610, 'Pierre Lefaucheux - Traversière', 7), (653141822, 'Île de la Jatte', 7), (2705338817, 'Victor Hugo - Gare', 7), (41610121, 'Censier - Jardin des Plantes', 7), (20278271464, 'Place des Ardoines', 7), (19130603957, 'Créteil Village', 7), (323486248, 'Montgallet - Reuilly', 7), (353462947, 'Richard Wallace - Place du 8 Mai 1945', 7), (27414578, 'Notre-Dame-des-Champs - Stanislas', 7), (653156540, 'Place de la Division Leclerc', 7), (275968458, 'Place du Président Salvador Allende', 7), (54000631, 'Victor Hugo - Bineau', 7), (457713145, 'Gare de Nanterre Ville', 7), (34235349, 'Jean Calvin - Tournefort', 7), (653042678, 'Quai de Béthune - Pont de la Tournelle', 7), (37848502, 'Pierre Brossolette - 12 Février 1934', 7), (102335085, 'Aristide Briand - Place de la Résistance', 7), (653135400, 'Paul Vaillant-Couturier - Gare RER', 7), (27363058, 'Suffren - La Motte-Piquet', 7), (27362896, 'Beffroy', 7), (82334007, 'Pascal - Claude Bernard', 7), (1064000778, "Gare d'Austerlitz - Pont Charles de Gaulle", 7), (2515618216, 'Hippodrome de Longchamp', 7), (308082350, 'Malakoff - Place de la Porte Maillot', 7), (12948189248, 'Guy Môquet - Jean Moulin', 7), (1062256852, 'Maxime Gorki - Louis Aragon', 7), (1314450240, 'Gare du Stade', 8), (11874261013, 'Place du 17 Octobre', 8), (13568870765, 'Place des Arts - Jean Mermoz', 8), (210584503, "Gare de l'Est - Fidélité", 8), (129043651, 'Roquette - Thiéré', 8), (394404659, 'Gare Saint-Lazare - Cour du Havre', 8), (213675430, 'Boutroux - Porte de Vitry', 8), (13356269, 'Assas - Rennes', 8), (15462236, 'Galilée - Kléber', 8), (16931052467, 'Jean Jaurès - Place de la Libération', 8), (11437706131, 'Bateliers - Quai de Seine', 8), (213686196, 'Lauriston - Copernic', 8), (20431005501, 'Quai des Célestins - Henri IV', 8), (11908510683, 'Séminaire de Conflans - Liberté', 8), (453172172, "Porte d'Italie", 8), (214114469, 'Gare de Nogent-le-Perreux', 8), (38192, 'La Motte-Picquet - Grenelle', 8), (48800374, "Place de l'Hôtel de Ville", 8), (349750111, 'Bleue - Trévise', 8), (37815993, 'Mutualité', 8), (102722579, 'Voltaire - Anatole France', 8), (20454506987, 'Pavé Grignon - Bretagne', 8), (1056715831, 'Marché Saint-Germain', 8), (1057774603, 'Marie-Georges Picquart - Pereire', 8), (653197324, 'Théâtre des Amandiers - Palais des sports', 8), (7295, 'Chevreuse - Montparnasse', 8), (544249939, 'Raspail - Chomel', 8), (100859941, 'Raspail - Bac', 8), (210566542, 'Square Boucicaut', 8), (620403530, 'Gabriel Péri - Danielle Casanova', 8), (20702544649, 'Avenue de la Paix - Chaillon', 8), (27363137, 'Hameau Fleuri - Marché', 8), (214119792, 'Gare RER - Malleret-Joinville', 8), (1057399900, 'Placette Grégoire Collas', 8), (121025345, "Chabrol - d'Hauteville", 8), (80419347, 'Lagny - Auguste Blanqui', 8), (1062802530, 'Niger - Soult', 9), (19179944124, 'Hôpital Mondor', 9), (2515829865, 'Basilique', 9), (17486274358, 'Jean Rostand - Paul Vaillant Couturier', 9), (230873471, 'Octave Feuillet - Albéric Magnard', 9), (17278902806, "Rouget de L'isle - Watteau", 9), (1558958733, 'Arche - Léonard de Vinci', 9), (224256188, 'Beaujon - Wagram', 9), (473204291, 'Victor Hugo - Magasins Généraux', 9), (129036192, "Gare de l'Est - Verdun", 9), (221038698, 'Mahatma Gandhi', 9), (392576677, 'Senard - Charles Blum', 9), (653079520, 'Averroès - Aimé Césaire', 9), (653129435, 'Neuilly - Petit', 9), (38280, 'Saint-Didier - Raymond Poincaré', 9), (303102719, 'Brancion - Lefebvre', 9), (210738704, 'Mazagran - Bonne Nouvelle', 9), (102745622, 'Raspail - Albert Schweitzer', 9), (369011098, 'Paris - Laitières', 9), (653137567, 'Place Saint-Just', 9), (131908132, 'Parc Eli Lotar', 9), (54000564, 'Paradis - Hauteville', 9), (19858721250, 'Université Paris Est Créteil', 9), (15463487, 'Pergolèse - Marbeau', 9), (27313492, 'Petites Ecuries - Faubourg Saint-Denis', 9), (54000537, 'Saint-Gilles - Turenne', 9), (653040243, 'Archives - Pastourelle', 9), (129080400, 'Belles Feuilles - Place de Mexico', 9), (6297, 'Victor Massé - Jean-Baptiste Pigalle', 9), (11146696292, 'Victor Hugo - Paul Eluard', 9), (653118283, 'Ancienne Mairie - André Morizet', 9), (124167835, 'Lavoisier - Missak Manouchian', 9), (653194214, 'Hôtel de Ville de Rueil-Malmaison', 9), (39149651, 'Richard Lenoir - Place de la Bastille', 9), (6295, 'Pontoise - La Tournelle', 9), (907054879, 'Liberté - Vert-de-Maisons', 9), (27415224, 'Bir Hakeim', 9), (19186120360, 'Haut du Mont-Mesly', 10), (129021753, 'Moncey - Blanche', 10), (210387163, 'Saint-Denis - Réaumur', 10), (11438049493, 'Hélène et François Missoffe - Emile Borel', 10), (19331872653, 'Bleuets - Bordières', 10), (18013122841, 'Port - Conflue

In [59]:
cur.execute("SELECT i.station_id,name,num_docks_available FROM station_info i INNER JOIN station_status s ON i.station_id=s.station_id ORDER BY num_docks_available")
print(cur.fetchall())

[(63498079, 'Marché Secrétan', 0), (102338493, 'Larmeroux - Baudelaire', 0), (101743895, 'Joseph Liouville - Croix Nivert', 0), (213694482, 'Botzaris - Parc des Buttes Chaumont', 0), (54000616, 'Pyrénées - Avron', 0), (21372728303, 'Place Daydé - Ile Seguin', 0), (9931940126, 'Diane Arbus', 0), (128932790, 'Arsène Houssaye - Champs-Elysées', 0), (235513935, 'Carducci - Place Hannah Arendt', 0), (102324803, 'Pyrénées - Emmery', 0), (20689981670, 'Roossevelt - Impasse du Marché', 0), (101751231, 'Saint-Amand - Labrouste', 0), (102323152, "Manin - Carrières d'Amérique", 0), (66491385, 'Fontenay - Libération', 0), (213987795, 'Wilson - Landy', 0), (13718041, 'Square Simon Bolivar', 0), (20682017769, 'Pierre-Simon Girard  - Paris', 0), (19495443023, 'Paul Bodin - Clichy', 0), (82332239, 'Ecoles - Carmes', 0), (129096696, 'Léon - Doudeauville', 0), (18976782828, 'Welovegreen', 0), (213682736, 'Morillons - Dantzig', 0), (54000619, 'Porte de Bagnolet', 0), (1057360420, 'Place Aimé Césaire', 0), (20703108288, 'Franklin Roosevelt - Kennedy', 0), (1057072168, 'Jules Guesdes - Général de Gaulle', 0), (1015246367, 'Champs-Elysees - Bassano', 0), (653086121, 'Louis Xavier de Ricard - Ancienne Mairie', 0), (100933541, 'Vivaldi - Antoine-Julien Hénard', 0), (653165196, 'Les Blagis', 0), (653083675, 'Maréchal Joffre - Verdun', 0), (98132679, 'Jean Bleuzen - Square du 11 Novembre', 0), (379063990, 'Place du 14 Juillet', 0), (12225289563, 'Béranger - Félix Faure', 0), (17869323774, 'Chastenet de Géry - Marcel Paul', 0), (27415411, 'Frères Flavien - Porte des Lilas', 0), (11438171152, 'Place Charles de Gaulle', 0), (11218473640, 'Bons Raisins - Voltaire', 0), (653193536, 'Maxime Gorki - Paul Vaillant-Couturier', 0), (74692052, 'Francoeur - Caulaincourt', 0), (39776330, 'Buzenval - Vignoles', 0), (27415194, 'Gergovie - Alésia', 0), (35147530, 'Pierre Levée - Fontaine Timbaud', 0), (129142199, 'Marcel Yol - Jullien', 0), (1057061349, 'Chancé Milly - Cimetière Communal Sud', 0), (27362949, 'Louis Blanc - Jemmapes', 0), (66491409, 'Guillaume Tell - Parc Henri Barbusse', 0), (82583924, 'Pyrénées - Charles Renouvier', 0), (210561800, 'Saint-Romain - Cherche-Midi', 0), (19989456853, 'Sydney Bechet - Jacques Gautier', 0), (19161093714, 'Evariste Galois', 0), (129069108, 'Paul Barruel - Vaugirard', 0), (284708999, 'Santé - Arago', 0), (13242682, 'Alexander Fleming - Belvédère', 0), (27414924, 'Sambre et Meuse - Villette', 0), (20699530917, 'Suresnes - Place du Souvenir Français', 0), (20458224375, 'Vivienne - Petits Champs', 0), (213693126, 'Véron - Lepic', 0), (66491406, 'Cours de Vincennes - Davout', 0), (129107656, 'Félix Ziem - Armand Gauthier', 0), (125918662, 'Marcadet - Ramey', 0), (1057228658, 'Youri Gagarine - Karl Marx', 0), (82571023, 'Alexandre Dumas - Place de la Réunion', 0), (13372702, 'Saint-Fargeau - Mortier', 0), (82566934, 'Brochant - Clichy', 0), (49829553, 'Legendre - Nollet', 0), (1063044618, 'Bas - Gabriel Péri', 0), (501862076, 'Place Nelson Mandela', 0), (39882420, 'Championnet.', 0), (11908496227, 'Gardenat Lapostol - Franklin Roosevelt', 0), (369644630, "Gare de l'Est - Faubourg-Saint-Martin", 0), (52453, 'Le Vau - Maurice Bertaux', 0), (1063000561, 'Gardenat-Lapostol - Velettes', 0), (30179848, 'Saint-Blaise - Mouraud', 0), (653140345, 'Édouard Vaillant - Place Jean Jaurès', 0), (54000538, 'Mairie du 3ème', 0), (1034247348, 'Place des Larris', 0), (82587428, "Dupont de l'Eure - Gambetta", 0), (11375742, 'Arsonval - Falguière', 0), (20636823021, 'Tourlaque - Damrémont', 0), (1035816937, 'Poissonniers - Nord', 0), (39878420, 'Pyrénées - Dagorno', 0), (66491408, 'Calmette', 0), (21372647186, 'Versailles', 0), (75641607, 'Blaise-Desgoffe - Vaugirard', 0), (35472299, 'Pyrénées - Plaine', 0), (20440192915, 'De Gaulle - Castelnau', 0), (21372781592, 'Bateliers - Hippodrome', 0), (129101773, 'Caulaincourt - Place Constantin Pecqueur', 0), (54000629, 'Commandant Charcot - Bretteville', 0), (1062833975, 'Froidevaux - Boulard', 0), (20637435296, 'Haxo - Darcy', 0), (2515738489, 'Eugène Reisz - Davout', 0), (3906153622, 'Argenteuil - Voltaire', 0), (2254322638, 'Verdun - Pierre et Marie Curie', 0), (66491407, 'Haies - Réunion', 0), (66491394, 'Square Saint-Ambroise', 0), (213692714, "Lepic - Armée d'Orient", 0), (27415469, 'Orteaux - Mouraud', 0), (39169029, 'Sorbier - Ménilmontant', 0), (129136818, "Square du Carrefour de l'Insurrection", 0), (255207155, 'Lassus - Delouvain', 0), (85123644, 'Pyrénées - Ménilmontant', 0), (120564786, 'Filles Saint-Thomas - Place de la Bourse', 0), (54000621, 'Ménilmontant - Père Lachaise', 0), (76121343, 'Abbé Groult - Convention', 0), (85118872, 'Indre - Prairies', 0), (17261310217, 'Saint-Germain - Verdun', 0), (129103849, 'Francoeur - Marcadet', 0), (16134083337, 'Maréchal Leclerc de Hauteclocque - Marché Buzenval', 0), (129119449, 'Ménilmontant - Pelleport', 0), (210748575, 'Gravelle - Route du Bac', 0), (230877798, 'Chartres - La Charbonnière', 0), (1063429705, 'Eugène Varlin - Place de la Paix', 0), (26958435, 'Square des Saint-Simoniens', 0), (82445192, 'Gare Montparnasse - René Mouchotte', 0), (1062179194, '18 juin 1940 - Buzenval', 0), (54000604, 'Ordener - Poissonniers', 0), (43247738, 'Ruisseau - Ordener', 0), (19006016846, 'Simon Bolivar - Henri Turot', 0), (101740379, 'Boulard - Daguerre', 0), (213700358, "Villiers de l'Isle Adam - Pyrénées", 0), (2515686699, 'Borrégo - Gambetta', 0), (21443204298, 'Coysevox - Lamarck', 0), (213702608, 'Boyer - Ménilmontant', 0), (875078767, 'Lieutenant Chauré - Etienne Marey', 0), (97677210, 'Parmentier - République', 0), (221047138, 'Pierre et Marie Curie - Julien Grimau', 1), (213680553, 'Adolphe Pinard - Victor Hugo', 1), (13105968, 'Le Brix et Mesmin - Jourdan', 1), (129094535, 'Porte de Saint-Ouen - Bessières', 1), (20636596293, 'Buisson Saint-Louis - Saint-Maur', 1), (20690183551, "Grilles - Honoré d'Estienne d'Orves", 1), (210586093, 'Dunkerque - Rocroy', 1), (18749423187, 'Jean Jaurès - Gare de Clamart', 1), (18795078746, 'Charcot - Benfleet', 1), (16659953198, 'Verger - Colonel Guichard', 1), (129025451, 'Douai - Bruxelles', 1), (457813746, 'Henri Barbusse - Stalingrad', 1), (50191171, 'Thionville - Ourcq', 1), (210740080, 'Gare du Nord - Hôpital Lariboisière', 1), (129048000, 'Saint-Maur - Roquette', 1), (209057581, 'Gabriel Péri - Francisco Ferrer', 1), (129089749, 'Brochant - Square des Batignolles', 1), (27415150, 'Bobillot - Paulin Mery', 1), (828134511, 'Porte de Vanves', 1), (596813170, 'Cimetière de Fontenay-sous-Bois', 1), (596872103, 'Lucie Aubrac - Fort', 1), (129067920, 'Mouton Duvernet - Général Leclerc', 1), (583178525, 'Boissière - Etienne Dolet', 1), (653175838, 'Gare de Chaville Rive Gauche', 1), (66491402, 'Marcadet - Barbès', 1), (213679512, 'Sibelle - Alésia', 1), (2515351285, 'Saint Lambert - Blomet', 1), (54000625, 'Repos - Cimetière du Père Lachaise', 1), (384370499, 'Place Charles Vallin', 1), (463297497, 'Marcelle - Thalie', 1), (27415665, 'Jean Jaurès - Salvador Allende', 1), (54000601, 'Jean-François Lépine - Stephenson', 1), (549876068, 'Villette - Belleville', 1), (42907187, 'Richard Lenoir - Voltaire', 1), (1062206433, 'Chemin Vert - Fraternité', 1), (39202840, 'Rochechouart - Martyrs', 1), (6399, 'Hautpoul - Jean Jaurès', 1), (129050965, 'Place de la République - Voltaire', 1), (214139374, 'Gare RER de Gentilly', 1), (4329844165, 'Tristan Tzara -  Tchaïkovski', 1), (42743053, 'Stephenson - Doudeauville', 1), (49859500, 'Charenton - Diderot', 1), (18890164656, 'Square de Choisy - Eastman', 1), (27415466, 'Jourdain - Place des Grandes Rigoles', 1), (213688824, 'Faustin Hélie - Desbordes-Valmore', 1), (85145704, 'Réunion - Avron', 1), (653062048, 'Gare du Nord - Place de Valenciennes', 1), (11437761399, 'Henri Barbusse - Bourguignons', 1), (217235307, 'Place Carnot', 1), (129125489, 'Piat - Parc de Belleville', 1), (6385, 'Petit - Manin', 1), (653065577, 'Gare du Nord - Demarquay', 1), (216473073, 'Tardieu - Chappe', 1), (82458977, 'Place Falguière', 1), (43155320, "Porte d'Orléans", 1), (129130397, 'Pierre Grenier - Pont de Billancourt', 1), (35642049, 'Jemmapes - Ecluses Saint-Martin', 1), (49039283, 'Carpeaux - Place Jacques Froment', 1), (20431134793, 'Château -République', 1), (213680917, 'Abbé Carton - Plantes', 1), (210754072, 'Place Jean Delay', 1), (2820744873, 'Pierre Larousse - Raymond Losserand', 1), (977409509, 'Vincennes - Douy-Delcupe', 1), (17451132826, "Epi d'Or - Chevilly", 1), (42517412, 'Gambetta - Saint Fargeau', 1), (6512, 'Porte de Ménilmontant', 1), (124402232, 'Belleville - Télégraphe', 1), (85120104, 'Pelleport - Belgrand', 1), (989753852, 'Square des Epinettes', 1), (516709288, 'Charonne - Robert et Sonia Delaunay', 1), (27369223, 'Maine - Antoine Bourdelle', 1), (70736110, 'Etienne Dolet - Place Maurice Chevalier', 1), (125469898, 'Square Léon', 1), (27363504, 'Jacquier - Didot', 1), (85162552, 'Fontainebleau - Edmond Michelet', 1), (452920451, 'Mont Valérien - Michel Salles', 1), (256124192, 'Belleville - Pyrénées', 1), (42588096, 'Bobillot - Moulin des Prés', 1), (19867919889, 'De Gaulle - Moulin', 1), (39536951, 'Vistule - Choisy', 1), (27415169, 'Nationale - Marcel Duchamp', 1), (82408364, 'Guillaume Bertrand - République', 1), (54000607, 'Convention - Saint-Charles', 1), (27415215, 'Romain Rolland', 1), (80077998, 'Lorraine - Jean Jaurès', 1), (39311270, 'Pasteur - Cotentin', 1), (653069115, 'Claude Vellefaux - Sambre et Meuse', 1), (19867354582, 'Verdun - Carnot', 1), (54001190, 'Mairie du 19ème', 1), (266052390, 'Melun - Jean Jaurès', 1), (54000624, 'Gambetta - Tourelles', 1), (268976295, 'Butte aux Cailles - Esperance', 1), (27415371, 'Charonne - Alexandre Dumas', 1), (1599921040, 'Jessaint - Marx Dormoy', 1), (82436057, 'Moulin de la Pointe', 1), (6497, 'Duhamel - André Gide', 1), (15411223, 'Dareau - Broussais', 1), (478593396, 'Jean Moulin - Paul Doumer', 1), (357491025, 'Place Centrale', 1), (54000583, 'Tombe Issoire - René Coty', 1), (102748267, 'Montreuil - République', 1), (52456, 'Pré Saint-Gervais - Lilas', 1), (1056995858, 'Gergovie - Vercingétorix', 1), (128928526, 'Clapeyron - Moscou', 1), (1057003116, 'Charles Lecocq - Lecourbe', 1), (1057081237, "Cimetière d'Issy-les-Moulineaux", 1), (390075668, 'Stade Georges Carpentier', 1), (653079135, 'Mazagran - Pierre de Coubertin', 1), (20458486160, 'Sérurier - Alphonse Aulard', 1), (285454061, 'Square de la rue Pixérécourt', 1), (214109662, 'Hôtel de ville de Fontenay-sous-Bois', 1), (653190196, 'LCL Campus - Place Oscar Niemeyer', 1), (1057179405, 'Résistance - Hoche', 1), (409364001, 'Ivry - Simone Weil', 1), (135806005, 'Mairie de Romainville', 1), (653135378, 'Amaury Duval - Gabriel Péri', 1), (7402, 'Roquette - Auguste Laurent', 1), (35101194, "Place de l'Insurrection d'Août 1944 ", 1), (102343591, 'Louis Pasteur - Albert Petit', 1), (1056947780, 'Faubourg Poissonnière - Dunkerque', 1), (52474, 'Belleville -  Pré Saint-Gervais', 1), (39151458, "Goutte d'or - Barbès", 1), (468354634, "Quai de l'Oise - Aisne", 1), (213692227, 'Square Louise Michel', 1), (94555589, 'Pierre et Marie Curie - Maurice Thorez', 1), (428088564, 'La Jarry - Place Diderot', 1), (221036108, 'Charonne - Bureau', 1), (38522, 'Douai - Pierre Fontaine', 1), (16899518505, 'Mariotte - Batignolles', 1), (17721073284, 'Mairie', 1), (653104215, 'Sorbier - Gasnier-Guy', 1), (54000599, 'Lemercier - Cardinet', 1), (129106450, 'Joseph Dijon - Ornano', 1), (129059516, 'Picpus - Louis Braille', 1), (100790494, 'Bréa - Raspail', 1), (15309045, 'Marché Saint-Quentin', 1), (27415547, 'Square Etienne Jarousse', 1), (81212212, 'Jean Jaurès - Jules Jacquemin', 1), (18013135935, 'Nicolaï - Charenton', 1), (101738550, 'Didot - Place de Moro-Giafferi', 1), (27414713, 'Landy - Heurtault', 1), (102307005, 'Villiers - Batignolles', 1), (17364417797, 'Decrès - Alésia', 1), (43247025, "Jardins d'Eole", 1), (75525462, 'Plantes - Moulin Vert', 1), (653089942, 'Poissonniers - Championnet', 1), (18013073681, "Gare de Sèvres - Ville d'Avray", 1), (15433394, 'Custine - Ramey', 1), (42275164, 'Reuilly - Daumesnil', 1), (66491379, 'Place des Abbesses', 1), (1063984816, 'Gare du Nord - La Chapelle', 1), (27414902, 'Louis Blanc - La Chapelle', 1), (2515672078, 'Petit - Georges Thill', 1), (1062882947, 'Bargue -  Dutot', 1), (1062982815, 'Gare de Bellevue', 1), (391845823, 'Candale - Mehul', 1), (653097126, 'Place Paul Delouvrier', 1), (1074095810, 'Maurice Payret-Dortail', 1), (653150828, 'Joffre - Aigle', 1), (129004826, 'Bellefond - Poissonnière', 2), (12959947458, 'Parc des Pierrettes', 2), (2705290225, 'Suresnes - Muette à Neuilly', 2), (19941915381, 'Gare RER - Canadiens', 2), (102326776, "Jardin de l'Hospice Debrousse", 2), (1074410417, 'Verdun - Carnot', 2), (213688169, 'Benjamin Godard - Victor Hugo', 2), (54000567, 'Montreuil - Voltaire', 2), (13341879803, 'Châteaudun - Place de la Liberté', 2), (129078200, 'Parc Georges Brassens - Brancion', 2), (19495456684, 'Commandant Schloesing - Pétrarque', 2), (2515774908, 'Val-Fleury', 2), (210580039, "Tour d'Auvergne - Rodier", 2), (54001024, 'Parmentier - Abel Rabaud', 2), (6298, 'Gare du Nord - Saint-Vincent de Paul', 2), (27033125, 'Pierre Ginier - Clichy', 2), (27399547, 'Dominique Pado - Croix Nivert', 2), (20636558756, 'Dunkerque - Maubeuge', 2), (261987383, 'Place Du Général De Gaulle', 2), (66491395, 'Daumesnil - Hébrard', 2), (101022698, 'Olympiades', 2), (101759167, 'Lecourbe - Convention', 2), (213695073, 'Hôpital Robert Debré', 2), (77773, 'Gare de Reuilly - Picpus', 2), (17047102542, 'Ménil - Argenteuil', 2), (254224239, 'Place Adolphe Cherioux - Vaugirard', 2), (653091206, 'Porte de Clignancourt - Ney', 2), (653110492, 'Danielle Casanova - Ledru-Rollin', 2), (129121741, 'Belleville - Couronnes', 2), (101742129, 'Cherche-Midi - Hôpital Necker', 2), (221041655, 'Porte de Clignancourt.', 2), (1333959209, 'Génie - Mozart', 2), (213992316, 'Square du Théâtre du Garde-Chasse', 2), (1810975577, 'Guy Môquet - Parvis Georges Marchais', 2), (50156117, 'Legendre - Dulong', 2), (82508970, 'Verdun - Adrien Damalix', 2), (653055097, 'Milton - Manuel', 2), (74858883, 'Pereire - Saussure', 2), (54000605, 'Mairie du 18ème', 2), (979059925, 'Bridaine - Lamandé', 2), (54000572, 'Diderot - Pierre Bourdan', 2), (302725495, 'Gare SNCF Vanves-Malakoff', 2), (571923059, 'Bordier - Félix Faure', 2), (102289046, 'Lourmel - Marie Skobtsov', 2), (20637420127, 'Monte Cristo - Bagnolet', 2), (210745258, 'Jean-Pierre Timbaud - Vaucouleurs', 2), (611152693, 'Tertres - Fontaine', 2), (63279, 'Siam - La Pompe', 2), (303102719, 'Brancion - Lefebvre', 2), (63769334, 'Emile Blemont - Poteau', 2), (2515403527, 'Saint-Cloud - Hippodrome', 2), (213681356, 'David Weill - Parc Montsouris', 2), (129087587, 'Legendre - Clichy', 2), (597245295, 'Concorde - Stalingrad', 2), (284711589, 'Beaumarchais - Pas de la Mule', 2), (27363162, 'Ranelagh - Mozart', 2), (1559700274, 'Square Gilbert Thomain', 2), (1062827573, 'Bézout - Général Leclerc', 2), (532054446, 'Richard Lenoir - Republique', 2), (18206879942, 'Rampal - Belleville', 2), (82565383, 'Jacques Kellner - Saint-Ouen', 2), (301841024, 'Molière - République', 2), (13497763, 'Ouest - Château ', 2), (1109534105, 'Demi-Lune - Aristide Briand', 2), (15189890802, 'Fontaine du Tertre - Calvaire', 2), (27363205, 'Porte de la Plaine', 2), (102313219, 'Belliard - Damrémont', 2), (20636665336, 'Tage - Italie', 2), (42541542, 'Gare Montparnasse - Edgar Quinet', 2), (66491391, 'Claude Vellefaux - Hôpital Saint-Louis', 2), (85155919, "Estienne d'Orves - Henri Ginoux", 2), (54000618, 'Pyrénées - Maraîchers', 2), (102314792, 'Etienne Jodelle - Saint Ouen', 2), (27364743, 'Marc Sangnier - Porte de Vanves', 2), (15291968, 'Place de Passy', 2), (17992442278, 'Place du 8 Mai 1945', 2), (213945171, 'Noisy le Sec - Jean-Baptiste Clément', 2), (125370566, 'Manin - Secrétan', 2), (2515658032, 'Clignancourt - Sofia', 2), (54000582, 'Edgar Quinet - Gaité', 2), (54000586, 'Pernety - Raymond Losserand', 2), (210585225, 'Dunkerque - Alsace', 2), (19183922057, 'Tolbiac - Boussingault', 2), (126354477, 'Clichy - Place Blanche', 2), (27415128, 'Ivry - Baudricourt', 2), (102304517, 'Pereire - Place de Wagram', 2), (570185777, 'Gare de Courbevoie', 2), (13373848216, 'Simone Signoret - Paris', 2), (1062812659, 'Auguste Blanqui - Glacière', 2), (12225158518, 'Henri Barbusse - Gabriel Péri', 2), (208795867, 'Ambroise Rendu - Porte Brunet', 2), (559507144, 'Place Jean Ferrat', 2), (100918666, 'Place Pasdeloup', 2), (653187900, 'Adolphe Lalyre - Armand Silvestre', 2), (49085250, 'Departement - Pajol', 2), (20430917761, 'Place des Fêtes - Solitaires', 2), (13373712848, 'Place de la Paix - Abbé Saint-Pierre', 2), (82568336, 'Jeanne Hornet - Girardot', 2), (17527065847, 'Chateau', 2), (102339791, 'Place du Maréchal de Lattre de Tassigny', 2), (1021553839, 'Faubourg Poissonniere - Delta', 2), (54000611, 'Manin - Simon Bolivar', 2), (484387018, 'Place du Maquis du Vercors', 2), (911767210, 'Alexandre Parodi - Quai de Valmy', 2), (599135701, 'Ramponeau - Belleville', 2), (102752610, 'Mairie de Bagnolet', 2), (82468690, 'Dutot - Place Alleray', 2), (54000623, 'Mairie du 20ème', 2), (491932748, 'Porte des Lilas - Faidherbe', 2), (76507850, 'Dantzig - Lefebvre', 2), (58311330, "Place des Droits de l'Enfant", 2), (362178041, 'Place Jules Ferry', 2), (15212034, 'Gérando - Rochechouart', 2), (27415389, 'Gambetta - Père Lachaise', 2), (653127524, 'Gustave Eiffel - Parc des Impressionnistes', 2), (58086242, 'Square des Amandiers', 2), (13373758036, 'Roland Garros - Jean Bouin', 2), (102311820, 'Clignancourt - Ordener', 2), (27415297, 'Square Raymond Souplex', 2), (27415179, 'Sarrette - Général Leclerc', 2), (41523981, 'Mairie du 15ème', 2), (1063012692, 'Kléber - National', 2), (82396562, 'Mairie du 10ème', 2), (1057302263, 'Place Nationale - Château-des-Rentiers', 2), (19183833298, 'Albert Kahn - Duhesme', 2), (82440673, 'Maine - Jean Zay', 2), (124390478, "Commandant l'Herminier - Gallieni", 2), (439750210, 'Italie - Jardin Joan Miro', 2), (54000595, 'Navier - Epinettes', 2), (1057290902, 'Cours de Vincennes - Soult', 2), (213682190, 'Place Jacques et Thérèse Tréfouël', 2), (75313725, 'Ferrus - Saint-Jacques', 2), (37995, 'Dom-Pérignon - Gravelle', 2), (653146273, 'Chausson - Gabriel Péri', 2), (35317080, 'Emile Reynaud - Porte de la Villette ', 2), (2515701705, 'Mûriers - Père Lachaise', 2), (27363206, 'Riquet - Marx Dormoy', 2), (20636530104, 'Dunkerque - Faubourg Saint-Denis', 2), (66491382, 'Guy Môquet - Compoint', 2), (82375611, 'Batignolles - Beudant', 2), (101491821, 'Jean Moulin - Place Victor et Hélène Basch', 2), (27415302, 'Michel-Ange - Parent de Rosan', 2), (129086648, 'Ceinture du Lac Inferieure - Saint-Cloud', 2), (214298601, 'Boyer-Barret - Raymond Losserand', 2), (54000589, 'Cambronne - Mademoiselle', 2), (292871105, 'Botzaris - Crimée', 2), (210749865, 'Port-Royal - Hôpital du Val-de-Grâce', 2), (54000622, 'Davout - Volga', 2), (11851103861, 'Division Leclerc - Kléber', 2), (1074060095, 'Lally-Tollendal - Armand Carrel', 2), (66491405, 'Charonne - Avron', 3), (52518, 'Louis Lumière.', 3), (74620630, 'Parc de Belleville - Julien Lacroix', 3), (521393180, 'Porte Pouchet-Bessières', 3), (129091653, 'Gare de Pont-Cardinet', 3), (36255, 'Toudouze - Clauzel', 3), (443402852, 'Place de Lévis', 3), (11004671601, 'Capitaine Glarner - Gabriel Péri', 3), (84983562, 'Roquette - Folie Regnault', 3), (54000597, 'Bayen - Pereire', 3), (422639331, 'Mairie de Neuilly sur Seine', 3), (82562496, 'Benjamin Delessert - Jean Lolive', 3), (210574471, 'Abbeville - Faubourg Poissonnière', 3), (101490103, 'Saint-Jacques - Tombe Issoire', 3), (125881065, 'Metz - Marne', 3), (20689987843, 'Vincennes - François Debergue', 3), (213689815, "Porte d'Asnières", 3), (125542925, 'Louis Blanc - Aqueduc', 3), (213694069, 'Flandre - Alphonse Karr', 3), (653059015, 'Bellefond - Maubeuge', 3), (30730, 'Place de la Nation - Charonne', 3), (54000600, 'Toqueville - Cardinet', 3), (5

In [73]:
cur.execute("SELECT SUM(num_docks_available)* 1.0/ SUM(num_bikes_available) AS mean_disponibility FROM station_status")
print(cur.fetchall())

[(Decimal('0.62053526342366604949'),)]

In [ ]:
cur.execute("SELECT SUM(num_docks_available) FROM station_status")
print(cur.fetchall())

[(0,)]

In [34]:
def get_station_info_data():
    url_info_station="https://velib-metropole-opendata.smovengo.cloud/opendata/Velib_Metropole/station_information.json"
    response_json=requests.get(url_info_station).json()
    json_structure(response_json)
    #print(response_json)
    #skim(pd.DataFrame(response_json["data"]))
    return response_json

In [35]:
def get_station_status_data():
    url_station_statut="https://velib-metropole-opendata.smovengo.cloud/opendata/Velib_Metropole/station_status.json"
    response_json=requests.get(  url_station_statut).json()
    json_structure(response_json)
    #skim(pd.DataFrame(response_json["data"]))
    return response_json

In [36]:
def store_data():
    
    pass

In [37]:
create_tables(cur)

In [38]:
station_info_json=get_station_info_data()
station_status_json=get_station_status_data()
station_info_json=station_info_json["data"]["stations"]
for dict_row in station_info_json:
    dict_row.pop("station_opening_hours",None)

lastUpdatedOther: int
ttl: int
data: dict
  stations: list
    [list of 1517]
      station_id: int
      stationCode: str
      name: str
      lat: float
      lon: float
      capacity: int
      station_opening_hours: NoneType
lastUpdatedOther: int
ttl: int
data: dict
  stations: list
    [list of 1517]
      station_id: int
      num_bikes_available: int
      numBikesAvailable: int
      num_bikes_available_types: list
        [list of 2]
          mechanical: int
      num_docks_available: int
      numDocksAvailable: int
      is_installed: int
      is_returning: int
      is_renting: int
      last_reported: int
      stationCode: str
      station_opening_hours: NoneType

In [39]:
for dict_row in station_info_json:
    if dict_row["stationCode"][0]=="0":
        print(dict_row["stationCode"])

In [40]:
df_station_info = pd.json_normalize(station_info_json)
df_station_info.head(1)

,station_id,stationCode,name,lat,lon,capacity,rental_methods
0,213688169,16107,Benjamin Godard - Victor Hugo,48.865983,2.275725,35,NaN

In [41]:
df_station_info = pd.json_normalize(station_info_json)
df_station_info

,station_id,stationCode,name,lat,lon,capacity,rental_methods
0,213688169,16107,Benjamin Godard - Victor Hugo,48.865983,2.275725,35,NaN
1,19179944124,40001,Hôpital Mondor,48.798922,2.453745,28,NaN
2,18795078746,32304,Charcot - Benfleet,48.878370,2.440524,28,NaN
3,36255,9020,Toudouze - Clauzel,48.879296,2.337360,21,[CREDITCARD]
4,251039991,14111,Cassini - Denfert-Rochereau,48.837526,2.336035,25,[CREDITCARD]
...,...,...,...,...,...,...,...
1512,523900881,19018,Cité de la Musique,48.888797,2.392581,60,[CREDITCARD]
1513,34742973,15056,Place Balard,48.836396,2.278419,22,[CREDITCARD]
1514,101013666,12105,Bercy - Villot,48.841795,2.376785,33,[CREDITCARD]
1515,315022587,8004,Malesherbes - Place de la Madeleine,48.870406,2.323244,67,[CREDITCARD]
1516,19697809404,8203,Matignon - Faubourg Saint-Honoré,48.871499,2.313896,35,NaN

In [42]:
df_station_status = pd.json_normalize(station_status_json["data"]["stations"])
df_station_status=df_station_status.drop(columns=["station_opening_hours","numDocksAvailable","numBikesAvailable"])
df_station_status

,station_id,num_bikes_available,num_bikes_available_types,num_docks_available,is_installed,is_returning,is_renting,last_reported,stationCode
0,213688169,2,"[{'mechanical': 1}, {'ebike': 1}]",33,1,1,1,1780998645,16107
1,19179944124,19,"[{'mechanical': 10}, {'ebike': 9}]",9,1,1,1,1780998687,40001
2,18795078746,1,"[{'mechanical': 0}, {'ebike': 1}]",27,1,1,1,1780998201,32304
3,36255,3,"[{'mechanical': 1}, {'ebike': 2}]",17,1,1,1,1780998638,9020
4,251039991,3,"[{'mechanical': 0}, {'ebike': 3}]",21,1,1,1,1780998551,14111
...,...,...,...,...,...,...,...,...,...
1512,523900881,20,"[{'mechanical': 8}, {'ebike': 12}]",39,1,1,1,1780998658,19018
1513,34742973,31,"[{'mechanical': 28}, {'ebike': 3}]",0,1,1,1,1780998726,15056
1514,101013666,29,"[{'mechanical': 21}, {'ebike': 8}]",4,1,1,1,1780998741,12105
1515,315022587,76,"[{'mechanical': 45}, {'ebike': 31}]",3,1,1,1,1780998692,8004
1516,19697809404,34,"[{'mechanical': 18}, {'ebike': 16}]",1,1,1,1,1780998713,8203

In [43]:
def pad_to_five(df): 
    new_station_code=[]
    for val in df["stationCode"].sort_values(ascending=True):
        if len(val)!=5:
            new_station_code.append((5-len(val))*"0"+val)
        else:
            new_station_code.append(val)
    df["stationCode"]=new_station_code
    return df

In [44]:
df_station_info=pad_to_five(df_station_info)
df_station_status=pad_to_five(df_station_status)

In [45]:
num_mechanicals_list=[]
num_ebikes_list=[]
for value in df_station_status["num_bikes_available_types"]:

    num_mechanicals_list.append(value[0]["mechanical"])
    num_ebikes_list.append(value[1]["ebike"])

df_station_status["num_mech_bikes"]=num_mechanicals_list
df_station_status["num_ebikes"]=num_ebikes_list
df_station_status=df_station_status.drop(columns=["num_bikes_available_types"])
df_station_status.head(1)

,station_id,num_bikes_available,num_docks_available,is_installed,is_returning,is_renting,last_reported,stationCode,num_mech_bikes,num_ebikes
0,213688169,2,33,1,1,1,1780998645,10003,1,1

In [46]:
station_status_insert=df_station_status.to_numpy().tolist()
station_status_insert[0:2]

[[213688169, 2, 33, 1, 1, 1, 1780998645, '10003', 1, 1],
 [19179944124, 19, 9, 1, 1, 1, 1780998687, '10004', 10, 9]]

In [47]:
cur.executemany("INSERT INTO station_status VALUES(%s,%s,%s,%s::boolean,%s::boolean,%s::boolean,%s,%s,%s,%s)", station_status_insert)

In [48]:
df_station_info.head(2)

,station_id,stationCode,name,lat,lon,capacity,rental_methods
0,213688169,10003,Benjamin Godard - Victor Hugo,48.865983,2.275725,35,NaN
1,19179944124,10004,Hôpital Mondor,48.798922,2.453745,28,NaN

In [49]:
station_info_to_insert=df_station_info.to_numpy().tolist()
station_info_to_insert[0:2]

[[213688169,
  '10003',
  'Benjamin Godard - Victor Hugo',
  48.865983,
  2.275725,
  35,
  nan],
 [19179944124,
  '10004',
  'Hôpital Mondor',
  48.798922410229,
  2.4537451531298,
  28,
  nan]]

In [50]:
cur.executemany("INSERT INTO station_info VALUES(%s,%s,%s,%s,%s,%s,%s)", station_info_to_insert)

In [51]:
#cur.execute("ROLLBACK")

In [67]:
cur.execute("SELECT * FROM station_info LIMIT 3")
print(cur.fetchall())

cur.execute("SELECT * FROM station_status LIMIT 3")
print(cur.fetchall())

[(213688169, '10003', 'Benjamin Godard - Victor Hugo', 48.865982, 2.275725, 35, 'NaN'), (19179944124, '10004', 'Hôpital Mondor', 48.798923, 2.4537451, 28, 'NaN'), (18795078746, '10005', 'Charcot - Benfleet', 48.87837, 2.4405239, 28, 'NaN')]
[(213688169, 2, 33, True, True, True, 1780998645, '10003', 1, 1), (19179944124, 19, 9, True, True, True, 1780998687, '10004', 10, 9), (18795078746, 1, 27, True, True, True, 1780998201, '10005', 0, 1)]

In [53]:
"""
1. Les stations les plus vides et les plus pleines (avec leur nom, donc avec une jointure).
2. Le taux de disponibilité moyen     (vélos rapportés à la capacité).
3. Les stations de grande capacité. """

'\n1. Les stations les plus vides et les plus pleines (avec leur nom, donc avec une jointure).\n2. Le taux de disponibilité moyen     (vélos rapportés à la capacité).\n3. Les stations de grande capacité. '