In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO
import psycopg2
from bs4 import BeautifulSoup
from collections import defaultdict, OrderedDict
import skimpy
import numpy as np
import math
import os
os.environ["PYTHONUTF8"] = "1"
os.environ["PGPASSFILE"] = ""

In [4]:

url_wiki="https://fr.wikipedia.org/wiki/Liste_des_départements_français_classés_par_population_et_superficie"

In [5]:
content_wiki=requests.get(url_wiki,headers = {
    'User-Agent': 'MonRobotFoot/1.0 (contact: monadresse@email.com) Python-requests'})
soup=BeautifulSoup(content_wiki.text)

In [6]:
table=soup.find("table",class_="wikitable")
sup_list=table.find_all("sup",class_="reference")
for sup in sup_list:
     sup.decompose()
#print("table: "+str(table))
tbody=table.find("tbody")
#print("tbody: "+str(tbody))
tr_list=tbody.find_all("tr")
list_rows=[]

for tr in tr_list:
    if tr.find("th")!= None:
         print("continue")
         continue
    #print("tr: "+str(tr))
    td_list=tr.find_all("td")
    #print("td_list:"+str(td_list))
    row=[]
    for num_col,td in enumerate(td_list):
        #print("td: "+str(td))
        if td.has_attr("colspan"):
            #print(td)
            colspan=td["colspan"]
            row.extend([None]*(int(colspan)-1))
        row.append(td.text.strip())
    if len(row)!=14:
            raise ValueError(f"Wrong col length: {len(row)} Values: {row}")    
    list_rows.append(row)
table_df=pd.DataFrame(list_rows)

continue
continue

In [7]:

table_df=table_df.rename(columns={1:"Numero_departement",2:"Nom",11:"Population"})
table_df=table_df[["Numero_departement","Nom","Population"]]
print(table_df.head(100))

   Numero_departement                                      Nom Population
0                  59                                     Nord  2 615 635
1                  75                                    Paris  2 103 778
2                  13                         Bouches-du-Rhône  2 087 658
3                 6AE         Collectivité européenne d'Alsace  1 934 548
4                  69  Circonscription départementale du Rhône  1 914 667
..                ...                                      ...        ...
95                 52                              Haute-Marne    168 331
96                 2A                             Corse-du-Sud    168 306
97                 04                  Alpes-de-Haute-Provence    168 054
98                 09                                   Ariège    155 722
99                 15                                   Cantal    144 196

[100 rows x 3 columns]

In [8]:
table_df["Population"]=table_df["Population"].str.replace("\xa0", "", regex=False)
print(table_df["Population"])

0      2615635
1      2103778
2      2087658
3      1934548
4      1914667
        ...
99      144196
100     143467
101     140255
102     115527
103      76486
Name: Population, Length: 104, dtype: str

In [9]:
print(table_df.to_string())

    Numero_departement                                      Nom Population
0                   59                                     Nord    2615635
1                   75                                    Paris    2103778
2                   13                         Bouches-du-Rhône    2087658
3                  6AE         Collectivité européenne d'Alsace    1934548
4                   69  Circonscription départementale du Rhône    1914667
5                   93                        Seine-Saint-Denis    1704316
6                   33                                  Gironde    1690493
7                   92                           Hauts-de-Seine    1654712
8                   44                         Loire-Atlantique    1487570
9                   78                                 Yvelines    1485086
10                  31                            Haute-Garonne    1471468
11                  77                           Seine-et-Marne    1468108
12                  62                            Pas-de-Calais    1457905
13                 69M                        Métropole de Lyon    1436354
14                  94                             Val-de-Marne    1426929
15                  91                                  Essonne    1338485
16                  38                                    Isère    1298990
17                  95                               Val-d'Oise    1281653
18                  76                           Seine-Maritime    1260964
19                  34                                  Hérault    1230289
20                  67                                 Bas-Rhin    1163810
21                  06                          Alpes-Maritimes    1128418
22                  35                          Ille-et-Vilaine    1120666
23                  83                                      Var    1119307
24                  57                                  Moselle    1051309
25                  29                                Finistère     933455
26                 974                               La Réunion     889679
27                  74                             Haute-Savoie     861158
28                  49                           Maine-et-Loire     833776
29                  60                                     Oise     829899
30                  56                                 Morbihan     783390
31                  42                                    Loire     774133
32                  30                                     Gard     770940
33                  68                                Haut-Rhin     770738
34                  54                       Meurthe-et-Moselle     732236
35                  85                                   Vendée     713609
36                  14                                 Calvados     709441
37                  64                     Pyrénées-Atlantiques     706564
38                  45                                   Loiret     691268
39                  01                                      Ain     679344
40                  17                        Charente-Maritime     672279
41                  63                              Puy-de-Dôme     664453
42                  37                           Indre-et-Loire     619362
43                  22                            Côtes-d'Armor     611859
44                  27                                     Eure     602714
45                  84                                 Vaucluse     572056
46                  72                                   Sarthe     566733
47                  80                                    Somme     565413
48                  51                                    Marne     563076
49                  71                           Saône-et-Loire     550310
50                  25                                    Doubs     547163
51                  21                                Côte-d'Or     540100
52                  26                                    Drôme     524207
53                  02                                    Aisne     523342
54                  50                                   Manche     497522
55                  66                      Pyrénées-Orientales     496855
56                 69D                                    Rhône     478313
57                  73                                   Savoie     448226
58                  86                                   Vienne     438897
59                  40                                   Landes     433570
60                  28                             Eure-et-Loir     433129
61                  24                                 Dordogne     417614
62                  81                                     Tarn     397352
63                 971                               Guadeloupe     384160
64                  11                                     Aude     379648
65                  79                              Deux-Sèvres     375229
66                  87                             Haute-Vienne     373167
67                 972                               Martinique     360630
68                  88                                   Vosges     357248
69                  16                                 Charente     352683
70                  07                                  Ardèche     334231
71                  47                           Lot-et-Garonne     333602
72                  03                                   Allier     333298
73                  89                                    Yonne     332267
74                  41                             Loir-et-Cher     328543
75                 976                                  Mayotte     310563
76                  10                                     Aube     310447
77                  53                                  Mayenne     305468
78                  18                                     Cher     298660
79                 973                                   Guyane     293996
80                  12                                  Aveyron     279609
81                  61                                     Orne     275201
82                  08                                 Ardennes     265893
83                  82                          Tarn-et-Garonne     265817
84                  39                                     Jura     257973
85                  19                                  Corrèze     240826
86                  70                              Haute-Saône     233185
87                  65                          Hautes-Pyrénées     231349
88                  43                              Haute-Loire     228654
89                  36                                    Indre     216069
90                  58                                   Nièvre     201417
91                  32                                     Gers     192645
92                  2B                              Haute-Corse     187180
93                  55                                    Meuse     180290
94                  46                                      Lot     176473
95                  52                              Haute-Marne     168331
96                  2A                             Corse-du-Sud     168306
97                  04                  Alpes-de-Haute-Provence     168054
98                  09                                   Ariège     155722
99                  15                                   Cantal     144196
100                 05                             Hautes-Alpes     143467
101                 90                    Territoire de Belfort     140255
102                 23                                   Creuse     115527
103                 48                                   Lozère      76486

In [10]:
table_df["Population"]=table_df["Population"].astype(int)

In [11]:

print(os.environ.get("APPDATA"))
print(os.environ.get("USERPROFILE"))

C:\Users\Utilisateur\AppData\Roaming
C:\Users\Utilisateur

In [2]:

conn = psycopg2.connect(host="localhost", user="postgres", password="jaune2000", port=5432)

In [3]:
conn=psycopg2.connect(user="postgres",host="localhost",password="jaune2000", port=5432,database="sandbox_db")
cur=conn.cursor()

In [ ]:
def create_tables(cur):
    cur.execute("DROP TABLE IF EXISTS bornes")
    cur.execute("DROP TABLE IF EXISTS departements CASCADE")

    query="""CREATE TABLE departements(
    code VARCHAR(5) PRIMARY KEY,
    nom VARCHAR(255),
    population INTEGER
    )"""
    cur.execute(query)


    query="""CREATE TABLE bornes(
    id BIGINT GENERATED ALWAYS AS IDENTITY, 
    nom_operateur VARCHAR(255),
    code_insee_commune VARCHAR(5),
    puissance_nominale FLOAT,
    code_departement VARCHAR(5) REFERENCES departements(code)

    )"""
    cur.execute(query)

In [15]:
create_tables(cur)

In [16]:
data_departements_to_insert=table_df.values.tolist()
cur.executemany("INSERT INTO departements VALUES (%s,%s,%s)",data_departements_to_insert)

In [17]:
cur.execute("SELECT * FROM departements LIMIT 5")
cur.fetchall()

[('59', 'Nord', 2615635),
 ('75', 'Paris', 2103778),
 ('13', 'Bouches-du-Rhône', 2087658),
 ('6AE', "Collectivité européenne d'Alsace", 1934548),
 ('69', 'Circonscription départementale du Rhône', 1914667)]

In [18]:

url_api="https://www.data.gouv.fr/api/1/datasets/5448d3e0c751df01f85d0572/"

api_json=requests.get(url_api).json()

In [19]:
url_data=api_json["resources"][0]["url"]

In [20]:
data_df=pd.read_csv(StringIO(requests.get(url_data).text))

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_21236\2529255909.py:1: DtypeWarning: Columns (0: code_insee_commune, 1: prise_type_ef, 2: prise_type_2, 3: prise_type_combo_ccs, 4: prise_type_chademo, 5: prise_type_autre, 6: paiement_acte, 7: paiement_cb, 8: reservation, 9: station_deux_roues) have mixed types. Specify dtype option on import or set low_memory=False.
  data_df=pd.read_csv(StringIO(requests.get(url_data).text))

In [21]:
data_bornes_df=data_df[["nom_operateur","code_insee_commune","puissance_nominale"]].copy()

In [22]:
cur.execute("SELECT * FROM bornes LIMIT 5")
cur.fetchall()

[]

In [23]:
def insert_into_tables(cur,data_bornes_df):
    data_borns_to_insert=data_bornes_df.values.tolist()
    cur.executemany("INSERT INTO bornes VALUES (DEFAULT,%s,%s,%s)",data_borns_to_insert)

In [24]:
def soft_float_to_int(serie):
        new_list=[]
        for value in serie:
            if isinstance(value,float):  #convert float to int if no number after decimal
                if value % 1 == 0:
                    value=int(value)
            new_list.append(value)        
        return pd.Series(new_list)

In [27]:
data_bornes_df["code_insee_commune"]

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
          ...
228491    59359
228492      NaN
228493      NaN
228494      NaN
228495      NaN
Name: code_insee_commune, Length: 228496, dtype: object

In [31]:
data_bornes_df["code_insee_commune"]=soft_float_to_int(data_bornes_df["code_insee_commune"].astype(object))

In [32]:
data_bornes_df["code_insee_commune"]=data_bornes_df["code_insee_commune"].astype(str)

In [33]:
data_bornes_df[data_bornes_df["code_insee_commune"].isna()].head(3)

  nom_operateur code_insee_commune  puissance_nominale
0   ChargePoint                NaN                22.0
1   ChargePoint                NaN                22.0
2   ChargePoint                NaN                11.0

In [35]:
def get_proportion_na(df):
    print("Valeurs manquantes: \n")  #comtpe valeurs manquantes
    for col in df.columns:
        nb_na=df[col].isna().sum()
        print(str(col)+" : "+str(nb_na)+" ("+str(nb_na/len(df)*100)+"%")

In [36]:
get_proportion_na(data_bornes_df)

Valeurs manquantes:

nom_operateur : 3985 (1.7440130242980183%
code_insee_commune : 66838 (29.251277921714163%
puissance_nominale : 0 (0.0%

In [37]:
for value in data_bornes_df["puissance_nominale"].unique():
    print(value)

22.0
11.0
44.0
36.0
14.8
200.0
50.0
300.0
22.08
150.0
60.0
100.0
400.0
240.0
560.0
3.4
7.4
3.7
24.0
30.0
7.3
120.0
75.0
7.0
360.0
180.0
7.36
149.999
22.078
30.4
2.3
11.04
3.68
90.0
0.0
1.84
38.4
21.888
2.88
14.72
3.0
6.0
4.6
2.2
5.5
43.0
160.0
350.0
250.0
14.0
600.0
280.0
29.0
307.0
150.4
29.6
40.0
25.0
20.0
18.0
62.5
66.0
320.0
47.0
500.0
32.0
375.0
132.0
352.0
2.0
72.0
144.0
116.0
108.0
156.0
88.0
232.0
192.0
225.0
148.0
94.0
110.0
164.0
326.0
172.0
52.0
678.0
1242.0
258.0
630.0
82.0
1500.0
372.0
900.0
170.0
118.0
38.0
7.328
210.0
62.0
184.0
63.0
23.0
26.0
27.0
130.0
80.0
3.5
42.0
158.0
211.0
113.0
239.0
396.0
105.0
176.0
53.0
91.0
101.0
12.0
1.6
220.0
2.299999952316284
7.400000095367432
16.0
104.0
204.0
9.0
114.0
64.0
21.0
19.0
444.0
44.4
124.0
175.0
165.0
1.8
14.49
3.22
20.01
3.681
4.0
49.999
43.47
6.9
149.997
119.1
54.0
480.0
1601.6
319.6
163.2
159.8
450.0
125.0
748.0
58.0
13.0
23.04
65.0
22.1
22.2
178.0
187.5
111.0
187.0
22.17025
146.0
10.0
70.0
181.0
39.0
86.0
0.0001
99.0
4.8
12.74789
109.0
149.5
169.0
7.2
51.0
1200.0
33.0
0.7
46.0
122.0
69.0
201.0
222.0
173.0
67.0
89.0
322.0
37.0
128.0
227.0
55.0
185.0
49.0
121.0
7.6
102.0
226.0
152.0
151.0
242.0
143.0
31.0
18.63
48.0
206.0
17.0
3.6
22.8
25.2
96.0
56.0
154.0
215.0
1.7
262.0
17.94
8.97
50.16
49.8
49.92
21.6
224.8
224.0
92.0
42.78
25.6
90.4
361.0
387.0
8.3
61.0
2.1
4.1
1.2
74.0
12800.0
16000.0
50.4
5.9
580.0
7360.0
3680.0
6900.0
50000.0
5750.0
1840.0
2530.0
5.0

In [38]:
data_bornes_df.head(5)

  nom_operateur code_insee_commune  puissance_nominale
0   ChargePoint                NaN                22.0
1   ChargePoint                NaN                22.0
2   ChargePoint                NaN                11.0
3   ChargePoint                NaN                11.0
4   ChargePoint                NaN                22.0

In [39]:
list_code_departement=[]
cur.execute("SELECT code FROM departements")
for row in cur.fetchall():
    list_code_departement.append(row[0])

code_commune_to_code_departement_list=[]
for code_commune in data_bornes_df["code_insee_commune"]:
    if not isinstance(code_commune,str):
        if math.isnan(code_commune):
            code_commune_to_code_departement_list.append(None)  
    elif code_commune[0:3] in list_code_departement:
        code_commune_to_code_departement_list.append(code_commune[0:3])
    elif code_commune[0:2] in list_code_departement:
        code_commune_to_code_departement_list.append(code_commune[0:2]) 
    else:
        code_commune_to_code_departement_list.append(None)

In [40]:
data_bornes_df["departement"]=code_commune_to_code_departement_list
data_bornes_df["departement"]=data_bornes_df["departement"].replace({np.nan: None})
data_bornes_df=data_bornes_df.replace({np.nan: None})
print(data_bornes_df["departement"].head(5))

0    None
1    None
2    None
3    None
4    None
Name: departement, dtype: object

In [ ]:
data_bornes_df.values.tolist()[0:5]

[['ChargePoint', None, 22.0, None],
 ['ChargePoint', None, 22.0, None],
 ['ChargePoint', None, 11.0, None],
 ['ChargePoint', None, 11.0, None],
 ['ChargePoint', None, 22.0, None]]

In [ ]:
"""for row in data_bornes_df.values.tolist():
    try:
        cur.execute("INSERT INTO bornes VALUES (DEFAULT,%s,%s,%s,%s)", row)
    except Exception as e:
        print("Failed row:", row)
        raise
"""

'for row in data_bornes_df.values.tolist():\n    try:\n        cur.execute("INSERT INTO bornes VALUES (DEFAULT,%s,%s,%s,%s)", row)\n    except Exception as e:\n        print("Failed row:", row)\n        raise\n'

In [42]:
cur.executemany("INSERT INTO bornes VALUES (DEFAULT,%s,%s,%s,%s)", data_bornes_df.values.tolist())

In [43]:
data_bornes_df["code_insee_commune"]

0          None
1          None
2          None
3          None
4          None
          ...
228491    59359
228492     None
228493     None
228494     None
228495     None
Name: code_insee_commune, Length: 228496, dtype: object

In [4]:
cur.execute("SELECT * FROM bornes LIMIT 10")
print(cur.fetchall())
cur.execute("SELECT * FROM departements LIMIT 5")
cur.fetchall()

[(1, 'ChargePoint', None, 22, None), (2, 'ChargePoint', None, 22, None), (3, 'ChargePoint', None, 11, None), (4, 'ChargePoint', None, 11, None), (5, 'ChargePoint', None, 22, None), (6, 'ChargePoint', None, 22, None), (7, 'ChargePoint', None, 22, None), (8, 'ChargePoint', None, 22, None), (9, 'ChargePoint', None, 22, None), (10, 'ChargePoint', None, 22, None)]

[('59', 'Nord', 2615635),
 ('75', 'Paris', 2103778),
 ('13', 'Bouches-du-Rhône', 2087658),
 ('6AE', "Collectivité européenne d'Alsace", 1934548),
 ('69', 'Circonscription départementale du Rhône', 1914667)]

In [47]:
#1. Le nombre de bornes pour 100 000 habitants, par département, du mieux au moins équipé.
cur.execute("SELECT d.nom,COUNT(*)::float/d.population*100000 as borne_centmille_hab FROM bornes b INNER JOIN departements d ON b.code_departement=d.code GROUP BY d.code ORDER BY borne_centmille_hab DESC")
print(cur.fetchall())

[('Vienne', 568.2426628571168), ('Calvados', 537.6063689580951), ('Aude', 427.76466621712746), ('Paris', 408.3130444371982), ('Tarn', 403.42064466770023), ('Hautes-Alpes', 393.12176319292934), ('Deux-Sèvres', 382.96613534668165), ('Manche', 382.6966445704914), ('Savoie', 362.09412216158813), ('Hautes-Pyrénées', 360.0620707243169), ('Drôme', 355.9662499737699), ('Yonne', 350.0197130620856), ("Côte-d'Or", 349.0094426957971), ('Corrèze', 326.37672012158157), ('Gironde', 324.1066363480949), ('Landes', 318.28770440759274), ('Alpes-de-Haute-Provence', 317.755007319076), ('Pyrénées-Orientales', 309.5470509504785), ('Haute-Marne', 308.91517308160707), ('Puy-de-Dôme', 291.0664862676517), ('Haute-Vienne', 288.34275270857285), ('Lozère', 287.63433831027896), ('Charente', 277.01930628921724), ('Saône-et-Loire', 276.3896712761898), ('Vosges', 275.71882837692584), ('Ain', 272.9103370310182), ('Lot-et-Garonne', 269.18303847099236), ('Allier', 269.1285276239281), ('Creuse', 267.46994209145913), ('Yvelines', 266.11253489696895), ('Vaucluse', 263.435747549191), ('Ariège', 260.0788584785708), ('Indre', 258.25083653832803), ('Haute-Savoie', 257.79241440014493), ('Seine-et-Marne', 256.0438332874693), ('Hérault', 255.1433037278233), ('Marne', 254.85014456307852), ('Nord', 254.50798754413367), ('Loire', 251.2488164178507), ('Seine-Maritime', 250.83983365107966), ('Cher', 250.45201901828167), ('Pas-de-Calais', 249.12460002537887), ('Tarn-et-Garonne', 243.77673361748873), ("Côtes-d'Armor", 242.86641203283762), ('Eure', 242.4035280414923), ('Pyrénées-Atlantiques', 242.01629293312425), ('Circonscription départementale du Rhône', 240.19842614929908), ('Eure-et-Loir', 237.80444163286228), ('Haute-Garonne', 237.5858666311466), ('Nièvre', 234.33970320280812), ('Moselle', 232.47208955692378), ('Maine-et-Loire', 230.99729423730116), ('Alpes-Maritimes', 228.4614389348628), ('Isère', 227.3304644377555), ('Oise', 226.53359023206437), ('Aube', 223.54862504710948), ('Bouches-du-Rhône', 223.26453854031647), ('Aveyron', 219.95000160939028), ('Dordogne', 219.8202167551854), ('Gard', 219.60204425765946), ('Loir-et-Cher', 214.58378355344658), ('Meurthe-et-Moselle', 208.94902736276282), ('Loire-Atlantique', 205.16681567926213), ('Morbihan', 205.00644634217952), ('Aisne', 203.88197392909416), ('Var', 203.34010240264737), ('Ille-et-Vilaine', 201.1303992447348), ('Territoire de Belfort', 197.4974154219101), ('Charente-Maritime', 196.7932956406492), ('Haut-Rhin', 196.17561350290242), ('Sarthe', 195.5065260007799), ('Bas-Rhin', 195.3067940643232), ('Essonne', 192.90466460214347), ('Doubs', 191.71617963933966), ('Val-de-Marne', 187.74585140536075), ('Somme', 187.47358125830146), ('Hauts-de-Seine', 185.95380948467167), ('Finistère', 175.36999641118211), ('Loiret', 171.42410758200873), ('Indre-et-Loire', 168.39909455213592), ('Ardèche', 164.85604267707066), ("Val-d'Oise", 164.78719278931192), ('Vendée', 164.5158623279695), ('Cantal', 163.66612111292963), ('Jura', 153.892073976734), ('Mayenne', 143.3865413071091), ('Haute-Saône', 138.51662842807212), ('Haute-Loire', 138.20007522282575), ('Lot', 137.13145920339088), ('Gers', 136.00145345064757), ('Meuse', 128.6815685839481), ('Orne', 124.9995457865342), ('Seine-Saint-Denis', 121.2216513838983), ('Corse-du-Sud', 117.64286478200421), ('Ardennes', 113.57952258991399), ('Haute-Corse', 79.60252163692702), ('Guadeloupe', 36.70345689296126), ('Martinique', 1.3864625793749827), ('La Réunion', 0.2248001807393453)]

In [48]:
#2. Les départements les plus sous-équipés.
cur.execute("SELECT d.nom,COUNT(*) FROM bornes b INNER JOIN departements d ON b.code_departement=d.code GROUP BY d.code ORDER BY COUNT(*) ASC")
print(cur.fetchall())

[('La Réunion', 2), ('Martinique', 5), ('Guadeloupe', 141), ('Haute-Corse', 149), ('Corse-du-Sud', 198), ('Lozère', 220), ('Meuse', 232), ('Cantal', 236), ('Lot', 242), ('Gers', 262), ('Territoire de Belfort', 277), ('Ardennes', 302), ('Creuse', 309), ('Haute-Loire', 316), ('Haute-Saône', 323), ('Orne', 344), ('Jura', 397), ('Ariège', 405), ('Mayenne', 438), ('Nièvre', 472), ('Haute-Marne', 520), ('Alpes-de-Haute-Provence', 534), ('Ardèche', 551), ('Indre', 558), ('Hautes-Alpes', 564), ('Aveyron', 615), ('Tarn-et-Garonne', 648), ('Aube', 694), ('Loir-et-Cher', 705), ('Cher', 748), ('Corrèze', 786), ('Hautes-Pyrénées', 833), ('Allier', 897), ('Lot-et-Garonne', 898), ('Dordogne', 918), ('Charente', 977), ('Vosges', 985), ('Eure-et-Loir', 1030), ('Indre-et-Loire', 1043), ('Doubs', 1049), ('Somme', 1060), ('Aisne', 1067), ('Haute-Vienne', 1076), ('Sarthe', 1108), ('Yonne', 1163), ('Vendée', 1174), ('Loiret', 1185), ('Charente-Maritime', 1323), ('Landes', 1380), ('Marne', 1435), ('Deux-Sèvres', 1437), ('Eure', 1461), ("Côtes-d'Armor", 1486), ('Vaucluse', 1507), ('Haut-Rhin', 1512), ('Saône-et-Loire', 1521), ('Meurthe-et-Moselle', 1530), ('Pyrénées-Orientales', 1538), ('Tarn', 1603), ('Morbihan', 1606), ('Savoie', 1623), ('Aude', 1624), ('Finistère', 1637), ('Gard', 1693), ('Pyrénées-Atlantiques', 1710), ('Ain', 1854), ('Drôme', 1866), ('Oise', 1880), ("Côte-d'Or", 1885), ('Manche', 1904), ('Maine-et-Loire', 1926), ('Puy-de-Dôme', 1934), ('Loire', 1945), ('Seine-Saint-Denis', 2066), ("Val-d'Oise", 2112), ('Haute-Savoie', 2220), ('Ille-et-Vilaine', 2254), ('Bas-Rhin', 2273), ('Var', 2276), ('Moselle', 2444), ('Vienne', 2494), ('Alpes-Maritimes', 2578), ('Essonne', 2582), ('Val-de-Marne', 2679), ('Isère', 2953), ('Loire-Atlantique', 3052), ('Hauts-de-Seine', 3077), ('Hérault', 3139), ('Seine-Maritime', 3163), ('Haute-Garonne', 3496), ('Pas-de-Calais', 3632), ('Seine-et-Marne', 3759), ('Calvados', 3814), ('Yvelines', 3952), ('Circonscription départementale du Rhône', 4599), ('Bouches-du-Rhône', 4661), ('Gironde', 5479), ('Nord', 6657), ('Paris', 8590)]

In [37]:
#3. L'opérateur dominant dans un département donné.
cur.execute("SELECT d.code, (SELECT b.nom_operateur FROM bornes b WHERE b.code_departement=d.code GROUP BY b.nom_operateur ORDER BY COUNT(*) DESC LIMIT 1) count_bornes FROM departements d") #nombre d'apaprition de l'opérateur par département
cur.fetchall()

[('59', 'Bouygues Energies & Services'),
 ('75', 'TotalEnergies Marketing France'),
 ('13', 'EVzen (SMEG DÃ©veloppement)'),
 ('6AE', None),
 ('69', 'IZIVIA'),
 ('93', 'SPIE CityNetworks'),
 ('33', 'TotalEnergies Charging Services'),
 ('92', 'IZIVIA'),
 ('44', 'Bouygues Energies & Services'),
 ('78', 'Bouygues Energies & Services'),
 ('31', 'Bouygues Energies & Services'),
 ('77', 'Bouygues Energies & Services'),
 ('62', 'Bouygues Energies & Services'),
 ('69M', None),
 ('94', 'Bouygues Energies & Services'),
 ('91', 'Bouygues Energies & Services'),
 ('38', 'EASYCHARGE'),
 ('95', 'IZIVIA'),
 ('76', 'Bouygues Energies & Services'),
 ('34', 'Bouygues Energies & Services'),
 ('67', 'Power Dot France'),
 ('06', 'IZIVIA'),
 ('35', 'Bouygues Energies et Services'),
 ('83', 'EASYCHARGE'),
 ('57', 'Power Dot France'),
 ('29', 'Bouygues Energies & Services'),
 ('974', 'Ezdrive'),
 ('74', 'EASYCHARGE'),
 ('49', 'Bouygues Energies & Services'),
 ('60', 'Bouygues Energies & Services'),
 ('56', 'Freshmile'),
 ('42', 'E-Totem'),
 ('30', 'Bouygues Energies & Services'),
 ('68', 'IZIVIA'),
 ('54', 'Power Dot France'),
 ('85', 'Bouygues Energies & Services'),
 ('14', 'Load Stations'),
 ('64', 'Citeos MobilitÃ© Electrique Paris - Cogelum IDF'),
 ('45', 'Power Dot France'),
 ('01', 'Tesla'),
 ('17', 'Citeos MobilitÃ© Electrique Paris - Cogelum IDF'),
 ('63', 'SPIE CityNetworks'),
 ('37', 'Power Dot France'),
 ('22', 'Bouygues Energies & Services'),
 ('27', 'SIEGE 27'),
 ('84', 'Citeos MobilitÃ© Electrique Paris - Cogelum IDF'),
 ('72', 'Allego'),
 ('80', 'Power Dot France'),
 ('51', 'Power Dot France'),
 ('71', 'Power Dot France'),
 ('25', 'EASYCHARGE'),
 ('21', 'Power Dot France'),
 ('26', 'EASYCHARGE'),
 ('02', 'Power Dot France'),
 ('50', 'Zunder (Grupo Easycharger S.A)'),
 ('66', 'Power Dot France'),
 ('69D', None),
 ('73', 'EASYCHARGE'),
 ('86', 'Soregies'),
 ('40', 'Citeos MobilitÃ© Electrique Paris - Cogelum IDF'),
 ('28', 'IZIVIA'),
 ('24', 'Citeos MobilitÃ© Electrique Paris - Cogelum IDF'),
 ('81', 'BOUYGUES ENERGIES SERVICES'),
 ('971', 'G-MOB'),
 ('11', 'Load Stations'),
 ('79', 'SEOLIS'),
 ('87', 'IZIVIA'),
 ('972', 'CAR2PLUG'),
 ('88', 'Power Dot France'),
 ('16', 'Citeos MobilitÃ© Electrique Paris - Cogelum IDF'),
 ('07', 'EASYCHARGE'),
 ('47', 'Citeos MobilitÃ© Electrique Paris - Cogelum IDF'),
 ('03', 'EASYCHARGE'),
 ('89', 'Citeos MobilitÃ© Electrique Paris - Cogelum IDF'),
 ('41', 'Greenflux'),
 ('976', None),
 ('10', 'Power Dot France'),
 ('53', 'Bouygues Energies & Services'),
 ('18', 'Allego'),
 ('973', None),
 ('12', 'Bouygues Energies & Services'),
 ('61', 'Power Dot France'),
 ('08', 'Power Dot France'),
 ('82', 'Power Dot France'),
 ('39', 'Power Dot France'),
 ('19', 'Citeos MobilitÃ© Electrique Paris - Cogelum IDF'),
 ('70', 'Citeos MobilitÃ© Electrique Paris - Cogelum IDF'),
 ('65', 'Load Stations'),
 ('43', 'EASYCHARGE'),
 ('36', 'TotalEnergies Marketing France'),
 ('58', 'Citeos MobilitÃ© Electrique Paris - Cogelum IDF'),
 ('32', 'Power Dot France'),
 ('2B', 'DRIVECO Partner Network'),
 ('55', 'Power Dot France'),
 ('46', 'Load Stations'),
 ('52', 'Power Dot France'),
 ('2A', 'DRIVECO Partner Network'),
 ('04', 'EASYCHARGE'),
 ('09', 'Load Stations'),
 ('15', 'Power Dot France'),
 ('05', 'EASYCHARGE'),
 ('90', 'Power Dot France'),
 ('23', 'Citeos MobilitÃ© Electrique Paris - Cogelum IDF'),
 ('48', 'Bouygues Energies & Services')]